# Generated by Django 6.1 on 2026-09-04 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='نام فایل نهایی بایگانی (بدون مسیر).', max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'در صف'), ('RUNNING', 'در حال اجرا'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('size', models.BigIntegerField(blank=True, help_text='حجم کل فایل بایگانی به بایت.', null=True)),
                ('database_size', models.BigIntegerField(blank=True, help_text='حجم فایل dump پایگاه داده به بایت.', null=True)),
                ('media_size', models.BigIntegerField(blank=True, help_text='حجم بایگانی فایل\u200cهای رسانه به بایت.', null=True)),
                ('includes_media', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 فایل نهایی بایگانی.', max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پشتیبان\u200cگیری',
                'verbose_name_plural': 'پشتیبان\u200cگیری\u200cها',
                'ordering': ['-created_at'],
                'permissions': [('create_backup', 'می\u200cتواند پشتیبان\u200cگیری جدید ایجاد کند'), ('download_backup', 'می\u200cتواند فایل پشتیبان را دانلود کند')],
            },
        ),
    ]
