# Generated by Django 6.1 on 2026-09-04 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='is_pre_restore_backup',
            field=models.BooleanField(default=False, help_text='پشتیبان امنیتی خودکار پیش از بازیابی.'),
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_filename', models.CharField(blank=True, max_length=255)),
                ('product_version', models.CharField(blank=True, max_length=50)),
                ('database_engine', models.CharField(blank=True, max_length=50)),
                ('database_backup_format', models.CharField(blank=True, max_length=50)),
                ('includes_media', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('QUEUED', 'در صف'), ('RESTORING', 'در حال بازیابی'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by_username', models.CharField(blank=True, max_length=150)),
                ('pre_restore_backup_filename', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='backup.backup')),
                ('pre_restore_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backup.backup')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_restores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازیابی',
                'verbose_name_plural': 'بازیابی\u200cها',
                'ordering': ['-created_at'],
                'permissions': [('restore_backup', 'می\u200cتواند پشتیبان را بازیابی کند')],
            },
        ),
    ]
