# Generated by Django 6.1 on 2026-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0007_backup_retention_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupretentionpolicy',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
