# Generated by Django 6.1 on 2026-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('ADMIN_OPERATOR', 'Admin Operator'), ('SUPPORT_OPERATOR', 'Support Operator'), ('REPAIR_OPERATOR', 'Repair Operator'), ('FINANCE_OPERATOR', 'Finance Operator'), ('WAREHOUSE_OPERATOR', 'Warehouse Operator'), ('MANAGER', 'Manager')], default='ADMIN_OPERATOR', max_length=30),
        ),
    ]
