# Generated by Django 6.1 on 2026-08-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='workflow.workflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'code'), name='unique_workflow_step_code'), models.UniqueConstraint(fields=('workflow', 'order'), name='unique_workflow_step_order')],
            },
        ),
    ]
