# Generated by Django 6.1 on 2026-08-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='workflowstep',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='workflowstep',
            name='unique_workflow_step_code',
        ),
        migrations.RemoveConstraint(
            model_name='workflowstep',
            name='unique_workflow_step_order',
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflow.workflowstep'),
        ),
    ]
