# Generated by Django 6.1 on 2026-08-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_workflowinstance_alter_workflowstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepexecution',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_executions', to='workflow.workflowinstance'),
        ),
    ]
