# Generated by Django 6.1 on 2026-08-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workflowstepexecution_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_instances', to='workflow.workflowstep'),
        ),
    ]
