# Generated by Django 6.1 on 2026-08-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_workflowinstance_current_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstance',
            name='is_active',
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_workflow_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده'), ('SUSPENDED', 'معلق')], default='ACTIVE', max_length=20),
        ),
    ]
