# Generated by Django 6.1 on 2026-08-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_remove_workflowinstance_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='workflow.workflowstep')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='workflow.workflowstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='workflow.workflow')),
            ],
            options={
                'ordering': ['workflow', 'from_step', 'to_step'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_executions', to='workflow.workflowinstance')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_transition_executions', to=settings.AUTH_USER_MODEL)),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflow.workflowtransition')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='unique_workflow_transition_code'),
        ),
    ]
