# Generated by Django 6.1 on 2026-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_workflowtransition_workflowtransitionexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmembership',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'مشاهده\u200cکننده'), ('EXECUTOR', 'مجری'), ('MANAGER', 'مدیر')], default='EXECUTOR', max_length=20),
        ),
    ]
