# Generated by Django 6.1 on 2026-08-09 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_workflowmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('VIEWER', 'مشاهده\u200cکننده'), ('EXECUTOR', 'مجری'), ('MANAGER', 'مدیر')], max_length=30, null=True)),
                ('action', models.CharField(choices=[('VIEW', 'مشاهده'), ('EXECUTE', 'اجرا'), ('TRANSITION', 'تغییر مرحله'), ('MANAGE', 'مدیریت')], max_length=20)),
                ('effect', models.CharField(choices=[('ALLOW', 'مجاز'), ('DENY', 'ممنوع')], default='ALLOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='workflow.workflowstep')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='workflow.workflowtransition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_permissions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='workflow.workflow')),
            ],
            options={
                'ordering': ['workflow', 'action'],
            },
        ),
    ]
