# Generated by Django 6.1 on 2026-08-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_workflowpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('field_type', models.CharField(choices=[('TEXT', 'متن'), ('TEXTAREA', 'متن چندخطی'), ('NUMBER', 'عدد'), ('DATE', 'تاریخ'), ('DATETIME', 'تاریخ و زمان'), ('BOOLEAN', 'بله/خیر'), ('SELECT', 'انتخابی')], default='TEXT', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='form_data', to='workflow.workflowinstance')),
            ],
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='form_definition', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='FieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('VIEWER', 'مشاهده\u200cکننده'), ('EXECUTOR', 'مجری'), ('MANAGER', 'مدیر')], max_length=20, null=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_access_rules', to='workflow.workflowstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_access_rules', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_rules', to='workflow.formfield')),
            ],
            options={
                'ordering': ['field'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='workflow.formdefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='workflow.formsection'),
        ),
        migrations.AddConstraint(
            model_name='formsection',
            constraint=models.UniqueConstraint(fields=('form', 'code'), name='unique_form_section_code'),
        ),
        migrations.AddConstraint(
            model_name='formsection',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='unique_form_section_order'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_form_field_code'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_form_field_order'),
        ),
    ]
