# Generated by Django 6.1 on 2026-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_formfield_formdata_formdefinition_fieldaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='code',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
