# Generated by Django 6.1 on 2026-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_alter_workflowstep_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtransition',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
