# Generated by Django 6.1 on 2026-08-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_alter_workflowtransition_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRepeatableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repeatable_groups', to='workflow.formsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='repeatable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='workflow.formrepeatablegroup'),
        ),
        migrations.AddConstraint(
            model_name='formrepeatablegroup',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_repeatable_group_code'),
        ),
        migrations.AddConstraint(
            model_name='formrepeatablegroup',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_repeatable_group_order'),
        ),
    ]
