# Generated by Django 6.1 on 2026-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_formrepeatablegroup_formfield_repeatable_group_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formfield',
            name='unique_form_field_order',
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(condition=models.Q(('repeatable_group__isnull', True)), fields=('section', 'order'), name='unique_form_field_order'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(condition=models.Q(('repeatable_group__isnull', False)), fields=('repeatable_group', 'order'), name='unique_repeatable_field_order'),
        ),
    ]
