# Generated by Django 6.1 on 2026-08-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_devicemodel_devicetype_device_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instancedevice',
            constraint=models.UniqueConstraint(fields=('instance', 'device'), name='unique_instance_device'),
        ),
    ]
