# Generated by Django 6.1 on 2026-08-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_instancedevice_unique_instance_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
