# Generated by Django 6.1 on 2026-08-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_instancedevice_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WORKFLOW_STARTED', 'شروع فرآیند'), ('STEP_ENTERED', 'ورود به مرحله'), ('TRANSITION_EXECUTED', 'تغییر مرحله'), ('ACTION_REQUIRED', 'نیاز به اقدام'), ('WORKFLOW_COMPLETED', 'تکمیل فرآیند'), ('WORKFLOW_CANCELLED', 'لغو فرآیند'), ('SLA_WARNING', 'هشدار SLA'), ('SLA_BREACHED', 'نقض SLA')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('transition_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='workflow.workflowtransitionexecution')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='workflow.workflowinstance')),
                ('workflow_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='workflow.workflowstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
