# Generated by Django 6.1 on 2026-08-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_businesscalendar_calendarexception_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('warning_before', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_slas', to='workflow.businesscalendar')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sla', to='workflow.workflowstep')),
            ],
        ),
    ]
