# Generated by Django 6.1 on 2026-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_workflowstepsla'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepexecution',
            name='sla_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='sla_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='sla_warning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='sla_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
