# Generated by Django 6.1 on 2026-08-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_workflowstepexecution_sla_breached_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepexecution',
            name='sla_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
