# Generated by Django 6.1 on 2026-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_formdata_is_submitted_formdata_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepexecution',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowstepexecution',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
