# Generated by Django 6.1 on 2026-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_workflowstepexecution_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده'), ('SUSPENDED', 'معلق')], default='ACTIVE', max_length=20),
        ),
    ]
