# Generated by Django 6.1 on 2026-08-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_workflowstep_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrepeatablegroup',
            name='group_type',
            field=models.CharField(choices=[('NORMAL', 'گروه معمولی'), ('DEVICE', 'گروه دستگاه\u200cها')], default='NORMAL', max_length=20),
        ),
    ]
