# Generated by Django 6.1 on 2026-08-21 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_formrepeatablegroup_group_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatableGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('VIEWER', 'مشاهده\u200cکننده'), ('EXECUTOR', 'مجری'), ('MANAGER', 'مدیر')], max_length=20, null=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_rules', to='workflow.formrepeatablegroup')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repeatable_group_access_rules', to='workflow.workflowstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repeatable_group_access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group'],
            },
        ),
    ]
