# Generated by Django 6.1 on 2026-08-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_repeatablegroupaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedevice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
