# Generated by Django 6.1 on 2026-08-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0032_instancedevice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='choice_label_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formfield',
            name='choice_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_fields', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='choice_parent_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_choice_fields', to='workflow.formfield'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='choice_source',
            field=models.CharField(choices=[('NONE', 'بدون منبع'), ('STATIC', 'گزینه\u200cهای ثابت'), ('MODEL', 'مدل سیستم')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='formfield',
            name='choice_value_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
