# Generated by Django 6.1 on 2026-08-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_formfield_choice_label_field_formfield_choice_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='choice_parent_model_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
