# Generated by Django 6.1 on 2026-08-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_rename_choice_parent_model_field_to_choice_filter_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaticChoiceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choice_source',
            field=models.CharField(choices=[('NONE', 'بدون منبع'), ('STATIC', 'گزینه\u200cهای ثابت'), ('LOOKUP', 'لیست داده\u200cای'), ('MODEL', 'مدل سیستم')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='formfield',
            name='choice_lookup_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_fields', to='workflow.lookuplist'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='choice_static_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_fields', to='workflow.staticchoiceset'),
        ),
        migrations.CreateModel(
            name='LookupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='workflow.lookupitem')),
                ('lookup_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='workflow.lookuplist')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lookup_list', 'value'), name='unique_lookup_item_value')],
            },
        ),
        migrations.CreateModel(
            name='StaticChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('choice_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='workflow.staticchoiceset')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('choice_set', 'value'), name='unique_static_choice_value')],
            },
        ),
    ]
