# Generated by Django 6.1 on 2026-08-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_lookuplist_staticchoiceset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='system_key',
            field=models.CharField(choices=[('NONE', 'بدون اتصال سیستمی'), ('DEVICE_TYPE', 'نوع دستگاه'), ('DEVICE_MODEL', 'مدل دستگاه'), ('IMEI', 'IMEI'), ('REPORTED_PROBLEM', 'شرح مشکل'), ('DESCRIPTION', 'توضیحات تکمیلی'), ('WARRANTY_STATUS', 'وضعیت گارانتی'), ('STATUS', 'وضعیت دستگاه')], default='NONE', max_length=30),
        ),
    ]
