# Generated by Django 6.1 on 2026-08-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_formfield_system_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceidentifier',
            name='is_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instancedevice',
            name='draft_device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_instance_devices', to='workflow.devicemodel'),
        ),
        migrations.AddField(
            model_name='instancedevice',
            name='draft_imei',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='instancedevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='workflow.device'),
        ),
    ]
