# Generated by Django 6.1 on 2026-08-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_deviceidentifier_is_committed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceidentifier',
            name='is_committed',
        ),
    ]
