# Generated by Django 6.1 on 2026-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_remove_deviceidentifier_is_committed'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_history_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
