# Generated by Django 6.1 on 2026-09-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_formfield_is_history_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtransition',
            name='to_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='workflow.workflowstep'),
        ),
    ]
