# Generated by Django 6.1 on 2026-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_make_to_step_nullable_for_finish_transitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowpermission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'مشاهده'), ('EXECUTE', 'اجرا'), ('START', 'شروع فرآیند'), ('TRANSITION', 'تغییر مرحله'), ('MANAGE', 'مدیریت')], max_length=20),
        ),
    ]
