# Generated by Django 6.1 on 2026-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_alter_workflowpermission_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatablegroupaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
