# Generated by Django 6.1 on 2026-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0043_add_repeatable_group_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrepeatablegroup',
            name='display_type',
            field=models.CharField(choices=[('LIST', 'لیست'), ('TABLE', 'جدول')], default='LIST', max_length=20),
        ),
    ]
