# Generated by Django 6.1 on 2026-09-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_add_repeatable_group_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedevice',
            name='draft_device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_instance_devices', to='workflow.devicetype'),
        ),
    ]
