# Generated by Django 6.1 on 2026-09-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0046_formfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'متن'), ('TEXTAREA', 'متن چندخطی'), ('NUMBER', 'عدد'), ('DATE', 'تاریخ'), ('DATETIME', 'تاریخ و زمان'), ('BOOLEAN', 'بله/خیر'), ('SELECT', 'انتخابی'), ('FORMULA', 'فرمول'), ('FILE', 'بارگذاری فایل')], default='TEXT', max_length=20),
        ),
    ]
