# Generated by Django 6.1 on 2026-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0052_historyconfiguration_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowpermission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'مشاهده'), ('EXECUTE', 'اجرا'), ('START', 'شروع فرآیند'), ('TRANSITION', 'تغییر مرحله'), ('MANAGE', 'مدیریت'), ('HISTORY', 'سوابق')], max_length=20),
        ),
    ]
