# Generated by Django 6.1 on 2026-09-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0053_alter_workflowpermission_action'),
        ('workflow', '0053_systembranding'),
    ]

    operations = [
    ]
