# Generated by Django 6.1 on 2026-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0065_workflowtransitionexecution_acceptance_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedevice',
            name='device_origin',
            field=models.CharField(blank=True, choices=[('EXISTING', 'دستگاه موجود'), ('NEW', 'دستگاه جدید')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workflowpermission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'مشاهده'), ('EXECUTE', 'اجرا'), ('START', 'شروع فرآیند'), ('TRANSITION', 'تغییر مرحله'), ('MANAGE', 'مدیریت'), ('STEP_ACTION', 'عملیات مرحله'), ('HISTORY', 'سوابق')], max_length=20),
        ),
    ]
