# Generated by Django 6.1 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0066_instancedevice_device_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='show_in_process_summary',
            field=models.BooleanField(default=False),
        ),
    ]
